### ISSUE TITLE
problems running complicated scripts from desktop files

### ISSUE THREAD

**Issue by mones** [Slesa/launchy#6]
Quoting original submitter at https://bugs.debian.org/799846:

> it looks like Launchy has problems to launch complex commands from 
> desktop files. Namely, I have experience these problems:
> 
> 1) Having a desktop file with Exec definition pointing to home directory using tilda - e.g.
> Exec=~/bin/script_name, Launchy is unable to launch the command (simply hitting Enter
> on the found item from the list does not trigger any action). PS: typing ~/bin/script_name
> directly in the Launchy window, the script is started. So the problem really seems to be 
> only when combined with a desktop file.
> 
> 2) If Exec in a desktop file contains sequence of commands separated by semicolon,
> Launchy only runs the first command. Although I have to admit I am not sure whether
> such an Exec is not against desktop file specifications, it looks like other launchers 
> treat this correctly.

Thanks,

**Comment by Slesa** [comment]
1) I tried to use both, ~ and $HOME, in a desktop file to start programs. But it even didn't work when called from Thunar.
2) The same for a sequence of commands in the exec entry. The commands are not recognized, nothing is started.

Seems as both issues are not part of the desktop file specification :(

**Comment by Slesa** [comment]
I tried it on SuSE with KDE, too. Here I get a syntax error within the .desktop file when starting from a console window. A double click doesn't start it either. I'm still not sure if I should break with standards here...

**Comment by Slesa** [comment]
@mones Do you have a hint for me?

**Comment by mones** [comment]
To be honest I hadn't realised that none of the reported problems are part of the desktop file specification [1], as you have checked. I don't think is a good idea to break standards, the Exec key should only expand the mandated % chars and look for command in $PATH if it's not an absolute path. For the rest a simple wrapper shell script can quickly be made, so I think the best hint I can give you is to close the bug, I'll do the same for the Debian one ;-)

Thanks for checking anyway!

[1] http://standards.freedesktop.org/desktop-entry-spec/latest/ar01s06.html

**Comment by mones** [comment]
To be honest I hadn't realised that none of the reported problems are part of the desktop file specification [1], as you have checked. I don't think is a good idea to break standards, the Exec key should only expand the mandated % chars and look for command in $PATH if it's not an absolute path. For the rest a simple wrapper shell script can quickly be made, so I think the best hint I can give you is to close the bug, I'll do the same for the Debian one ;-)

Thanks for checking anyway!

[1] http://standards.freedesktop.org/desktop-entry-spec/latest/ar01s06.html

**Comment by mones** [comment]
To be honest I hadn't realised that none of the reported problems are part of the desktop file specification [1], as you have checked. I don't think is a good idea to break standards, the Exec key should only expand the mandated % chars and look for command in $PATH if it's not an absolute path. For the rest a simple wrapper shell script can quickly be made, so I think the best hint I can give you is to close the bug, I'll do the same for the Debian one ;-)

Thanks for checking anyway!

[1] http://standards.freedesktop.org/desktop-entry-spec/latest/ar01s06.html

**Comment by mones** [comment]
To be honest I hadn't realised that none of the reported problems are part of the desktop file specification [1], as you have checked. I don't think is a good idea to break standards, the Exec key should only expand the mandated % chars and look for command in $PATH if it's not an absolute path. For the rest a simple wrapper shell script can quickly be made, so I think the best hint I can give you is to close the bug, I'll do the same for the Debian one ;-)

Thanks for checking anyway!

[1] http://standards.freedesktop.org/desktop-entry-spec/latest/ar01s06.html
