### ISSUE TITLE
Could not find or load the Qt platform plugin "windows "error

### ISSUE THREAD

**Issue by crazy-max** [Slesa/launchy#9]
Launchy v2.9.1-pre.1

![image](https://user-images.githubusercontent.com/1951866/27958391-1a471ee8-6323-11e7-8dd1-fcea9ec32a7d.png)

**Comment by Slesa** [comment]
Is this the installation over an existing one? I just installed it on my new laptop w/o error message.

**Comment by crazy-max** [comment]
It's a fresh install (Win 10 Pro x64)

**Comment by Jofagi** [comment]
I got the same error, Windows version is 10 1607.
On my system it's not exactly a fresh install. Launchy v2.5.0 got installed to %programfiles(x86)% and the new installer put its files into %programfiles%.

**Comment by Slesa** [comment]
I have updated the installer. Could you please retry?

**Comment by crazy-max** [comment]
Yep it works now thx
